package com.smartfinance.backend.dto.analysis;

import java.math.BigDecimal;
import java.util.List;

/**
 * Full financial snapshot for one user/period, returned by {@code GET /api/analysis/summary}.
 *
 * <p>This single response feeds the entire dashboard (balance card, stats cards, the
 * income-vs-expense chart, the category-distribution chart and the recent-transactions list) so
 * the frontend never needs more than one call per period.
 *
 * @param periodYear                resolved year of the analyzed period
 * @param periodMonth               resolved month of the analyzed period (1-12)
 * @param totalIncome               total income recorded in the period
 * @param totalExpense              total expense recorded in the period, including expenses
 *                                  generated by paying a recurring service (they are regular
 *                                  {@code expenses} rows, see {@code Expense#getRecurringPayment()})
 * @param savings                   {@code totalIncome - totalExpense}
 * @param expenseRatio              {@code totalExpense / totalIncome} (0 when income is 0)
 * @param expenseAlert              {@code true} when {@code expenseRatio > 0.80}
 * @param totalDebt                 sum of {@code remainingAmount} across all of the user's debts
 * @param debtRatio                 {@code totalDebt / totalIncome} (0 when income is 0)
 * @param annualSavingsProjection   {@code savings * 12}
 * @param topCategories             expense-by-category ranking for the period, highest first
 * @param monthlySeries             income vs. expense for the period and the 5 prior months,
 *                                  oldest first
 * @param recentTransactions        last 10 income/expense records combined, most recent first
 */
public record AnalysisSummaryResponse(
        int periodYear,
        int periodMonth,
        BigDecimal totalIncome,
        BigDecimal totalExpense,
        BigDecimal savings,
        BigDecimal expenseRatio,
        boolean expenseAlert,
        BigDecimal totalDebt,
        BigDecimal debtRatio,
        BigDecimal annualSavingsProjection,
        List<TopCategoryResponse> topCategories,
        List<MonthlySeriesPoint> monthlySeries,
        List<RecentTransactionResponse> recentTransactions
) {
}
