package com.smartfinance.backend.analisis.service;

import com.smartfinance.backend.analisis.model.dto.AnalysisSummaryResponse;
import com.smartfinance.backend.analisis.model.dto.MonthlySeriesPoint;
import com.smartfinance.backend.analisis.model.dto.RecentTransactionResponse;
import com.smartfinance.backend.analisis.model.dto.RecommendationResponse;
import com.smartfinance.backend.analisis.model.dto.RecommendationType;
import com.smartfinance.backend.analisis.model.dto.Severity;
import com.smartfinance.backend.analisis.model.dto.TopCategoryResponse;
import com.smartfinance.backend.common.repository.MonthlyTotalProjection;
import com.smartfinance.backend.gastos.model.entity.Expense;
import com.smartfinance.backend.ingresos.model.entity.Income;
import com.smartfinance.backend.gastos.repository.CategoryTotalProjection;
import com.smartfinance.backend.deudas.repository.DebtRepository;
import com.smartfinance.backend.gastos.repository.ExpenseRepository;
import com.smartfinance.backend.analisis.repository.FinancialAnalysisRepository;
import com.smartfinance.backend.ingresos.repository.IncomeRepository;
import com.smartfinance.backend.tarjetas.repository.CreditCardRepository;
import com.smartfinance.backend.common.security.SecurityUtils;
import org.springframework.data.domain.PageRequest;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.time.LocalDate;
import java.time.YearMonth;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.stream.Collectors;
import java.util.stream.Stream;

/**
 * Computes the financial analysis snapshot and rule-based recommendations for the current
 * user, backing {@code GET /api/analysis/summary} and {@code GET /api/analysis/recommendations}.
 *
 * <p>Every calculation resolves the caller via {@link SecurityUtils#getCurrentUserId()} and is
 * scoped strictly to that user's data — there is no cross-user aggregation anywhere in this
 * class.
 *
 * <p>{@link #getSummary} treats {@code totalExpense} as already including expenses generated by
 * paying a recurring service: {@code PATCH /api/recurring/{id}/pay} (Sprint 3) inserts a real
 * row into {@code expenses} with {@code recurring_payment_id} set, so summing {@code expenses}
 * for the period automatically counts them — no separate recurring-payment aggregation is
 * needed here.
 *
 * <p>"Active debt" uses {@code Debt#getRemainingAmount()} (see {@link DebtRepository#sumRemainingAmountByUser}),
 * not {@code totalAmount}: {@link com.smartfinance.backend.deudas.model.entity.Debt} has no
 * {@code status}/{@code isActive} flag, and a fully-paid debt naturally contributes {@code 0} to
 * the sum once its {@code remainingAmount} reaches {@code 0}.
 *
 * <p>{@code totalDebt} additionally sums {@code currentBalance} across every credit card owned
 * by the user (see {@link CreditCardRepository#sumCurrentBalanceByUser}), Fase B.2's cross-domain
 * integration: revolving credit card debt counts toward {@code debtRatio} the same way a
 * {@link com.smartfinance.backend.deudas.model.entity.Debt} does. Purely additive — a user with
 * no cards contributes {@code 0}, so {@code debtRatio} is unchanged from before this integration.
 */
@Service
public class FinancialAnalysisService {

    private static final BigDecimal EXPENSE_ALERT_THRESHOLD = new BigDecimal("0.80");
    private static final BigDecimal TOP_CATEGORY_INCOME_THRESHOLD = new BigDecimal("0.30");
    private static final BigDecimal DEBT_RATIO_ALERT_THRESHOLD = new BigDecimal("0.40");
    private static final BigDecimal LOW_SAVINGS_RATIO_THRESHOLD = new BigDecimal("0.10");
    private static final int RATIO_SCALE = 4;
    private static final int RECENT_TRANSACTIONS_LIMIT = 10;
    private static final int MONTHLY_SERIES_LENGTH = 6;

    /**
     * Case-insensitive substring terms used to detect a "food" category by name, since
     * categories are per-user and freely named (no global seeded category set exists to match
     * against by id) — see {@code Category} Javadoc.
     */
    private static final List<String> FOOD_CATEGORY_TERMS = List.of(
            "comida", "alimentacion", "alimentación", "mercado", "supermercado", "restaurante"
    );

    private final IncomeRepository incomeRepository;
    private final ExpenseRepository expenseRepository;
    private final DebtRepository debtRepository;
    private final CreditCardRepository creditCardRepository;
    private final FinancialAnalysisRepository financialAnalysisRepository;

    public FinancialAnalysisService(
            IncomeRepository incomeRepository,
            ExpenseRepository expenseRepository,
            DebtRepository debtRepository,
            CreditCardRepository creditCardRepository,
            FinancialAnalysisRepository financialAnalysisRepository
    ) {
        this.incomeRepository = incomeRepository;
        this.expenseRepository = expenseRepository;
        this.debtRepository = debtRepository;
        this.creditCardRepository = creditCardRepository;
        this.financialAnalysisRepository = financialAnalysisRepository;
    }

    @Transactional
    public AnalysisSummaryResponse getSummary(Integer year, Integer month) {
        Long userId = SecurityUtils.getCurrentUserId();
        YearMonth period = resolvePeriod(year, month);
        AnalysisSummaryResponse summary = computeSummary(userId, period);

        Long topCategoryId = summary.topCategories().isEmpty() ? null : summary.topCategories().get(0).categoryId();
        financialAnalysisRepository.upsertSnapshot(
                userId, period.getYear(), period.getMonthValue(),
                summary.totalIncome(), summary.totalExpense(), summary.savings(),
                summary.expenseRatio(), summary.debtRatio(), topCategoryId
        );

        return summary;
    }

    /**
     * Same computation as {@link #getSummary}, without refreshing the {@code financial_analysis}
     * snapshot. {@link #getRecommendations} needs the summary purely to evaluate its rules and
     * has no business writing a row every time it is called — {@link #getSummary} already
     * refreshes the snapshot on every dashboard load, so nothing reads a stale snapshot because
     * recommendations skip the upsert here.
     */
    private AnalysisSummaryResponse computeSummary(Long userId, YearMonth period) {
        LocalDate periodStart = period.atDay(1);
        LocalDate periodEnd = period.atEndOfMonth();

        BigDecimal totalIncome = nullSafe(incomeRepository.sumAmountByUserAndPeriod(userId, periodStart, periodEnd));
        BigDecimal totalExpense = nullSafe(expenseRepository.sumAmountByUserAndPeriod(userId, periodStart, periodEnd));
        BigDecimal savings = totalIncome.subtract(totalExpense);

        BigDecimal expenseRatio = safeDivide(totalExpense, totalIncome);
        boolean expenseAlert = expenseRatio.compareTo(EXPENSE_ALERT_THRESHOLD) > 0;

        BigDecimal totalDebt = nullSafe(debtRepository.sumRemainingAmountByUser(userId))
                .add(nullSafe(creditCardRepository.sumCurrentBalanceByUser(userId)));
        BigDecimal debtRatio = safeDivide(totalDebt, totalIncome);

        BigDecimal annualSavingsProjection = savings.multiply(BigDecimal.valueOf(12));

        List<TopCategoryResponse> topCategories = buildTopCategories(
                expenseRepository.findTopCategoriesByUserAndPeriod(userId, periodStart, periodEnd), totalExpense
        );
        List<MonthlySeriesPoint> monthlySeries = buildMonthlySeries(userId, period);
        List<RecentTransactionResponse> recentTransactions = buildRecentTransactions(userId);

        return new AnalysisSummaryResponse(
                period.getYear(), period.getMonthValue(),
                totalIncome, totalExpense, savings,
                expenseRatio, expenseAlert,
                totalDebt, debtRatio, annualSavingsProjection,
                topCategories, monthlySeries, recentTransactions
        );
    }

    @Transactional
    public List<RecommendationResponse> getRecommendations(Integer year, Integer month) {
        Long userId = SecurityUtils.getCurrentUserId();
        YearMonth period = resolvePeriod(year, month);
        AnalysisSummaryResponse summary = computeSummary(userId, period);
        return buildRecommendations(summary);
    }

    private List<RecommendationResponse> buildRecommendations(AnalysisSummaryResponse summary) {
        List<RecommendationResponse> recommendations = new ArrayList<>();
        boolean hasIncome = summary.totalIncome().compareTo(BigDecimal.ZERO) > 0;

        if (summary.expenseRatio().compareTo(EXPENSE_ALERT_THRESHOLD) > 0) {
            recommendations.add(new RecommendationResponse(
                    RecommendationType.ALERT, Severity.HIGH, null,
                    "Tus gastos superan el 80% de tus ingresos este mes. Revisa tu presupuesto cuanto antes."
            ));
        }

        if (hasIncome && !summary.topCategories().isEmpty()) {
            TopCategoryResponse topCategory = summary.topCategories().get(0);
            BigDecimal categoryIncomeRatio = safeDivide(topCategory.totalAmount(), summary.totalIncome());
            if (categoryIncomeRatio.compareTo(TOP_CATEGORY_INCOME_THRESHOLD) > 0) {
                if (isFoodCategory(topCategory.categoryName())) {
                    recommendations.add(new RecommendationResponse(
                            RecommendationType.RECOMMENDATION, Severity.MEDIUM, topCategory.categoryId(),
                            "Estás destinando más del 30% de tus ingresos a '" + topCategory.categoryName()
                                    + "'. Considera reducir tus gastos en comida."
                    ));
                } else {
                    recommendations.add(new RecommendationResponse(
                            RecommendationType.RECOMMENDATION, Severity.MEDIUM, topCategory.categoryId(),
                            "Tu categoría con mayor gasto, '" + topCategory.categoryName()
                                    + "', supera el 30% de tus ingresos este mes."
                    ));
                }
            }
        }

        if (hasIncome && summary.debtRatio().compareTo(DEBT_RATIO_ALERT_THRESHOLD) > 0) {
            recommendations.add(new RecommendationResponse(
                    RecommendationType.ALERT, Severity.HIGH, null,
                    "Tu nivel de endeudamiento supera el 40% de tus ingresos. Evita adquirir nuevas deudas."
            ));
        }

        if (summary.savings().compareTo(BigDecimal.ZERO) < 0) {
            recommendations.add(new RecommendationResponse(
                    RecommendationType.ALERT, Severity.HIGH, null,
                    "Tus gastos superaron tus ingresos este mes: tu ahorro es negativo."
            ));
        } else if (hasIncome) {
            BigDecimal savingsRatio = safeDivide(summary.savings(), summary.totalIncome());
            if (savingsRatio.compareTo(LOW_SAVINGS_RATIO_THRESHOLD) < 0) {
                recommendations.add(new RecommendationResponse(
                        RecommendationType.RECOMMENDATION, Severity.LOW, null,
                        "Tu ahorro este mes es bajo. Intenta ahorrar al menos el 10% de tus ingresos."
                ));
            }
        }

        if (recommendations.isEmpty()) {
            recommendations.add(new RecommendationResponse(
                    RecommendationType.INFO, Severity.LOW, null,
                    "Tus finanzas están saludables este mes. ¡Sigue así!"
            ));
        }

        return recommendations;
    }

    private List<TopCategoryResponse> buildTopCategories(
            List<CategoryTotalProjection> categoryTotals, BigDecimal totalExpense
    ) {
        return categoryTotals.stream()
                .map(projection -> new TopCategoryResponse(
                        projection.getCategoryId(),
                        projection.getCategoryName() != null ? projection.getCategoryName() : "Sin categoría",
                        projection.getTotal(),
                        safeDivide(projection.getTotal(), totalExpense)
                ))
                .toList();
    }

    /**
     * Builds the {@value #MONTHLY_SERIES_LENGTH}-month income-vs-expense series ending at
     * {@code currentPeriod} with two grouped queries (one per repository) covering the whole
     * window, instead of one {@code sumAmountByUserAndPeriod} call per month per repository —
     * {@value #MONTHLY_SERIES_LENGTH} months previously meant {@code 2 * MONTHLY_SERIES_LENGTH}
     * round trips. Months with no income/expense rows are absent from the grouped result, so they
     * are filled in as {@link BigDecimal#ZERO} here to keep exactly
     * {@value #MONTHLY_SERIES_LENGTH} points in chronological order, unchanged from before.
     */
    private List<MonthlySeriesPoint> buildMonthlySeries(Long userId, YearMonth currentPeriod) {
        YearMonth oldestPeriod = currentPeriod.minusMonths(MONTHLY_SERIES_LENGTH - 1);
        LocalDate seriesStart = oldestPeriod.atDay(1);
        LocalDate seriesEnd = currentPeriod.atEndOfMonth();

        Map<YearMonth, BigDecimal> incomeByMonth = groupTotalsByMonth(
                incomeRepository.sumAmountByUserGroupedByMonth(userId, seriesStart, seriesEnd)
        );
        Map<YearMonth, BigDecimal> expenseByMonth = groupTotalsByMonth(
                expenseRepository.sumAmountByUserGroupedByMonth(userId, seriesStart, seriesEnd)
        );

        List<MonthlySeriesPoint> series = new ArrayList<>(MONTHLY_SERIES_LENGTH);
        for (int offset = MONTHLY_SERIES_LENGTH - 1; offset >= 0; offset--) {
            YearMonth point = currentPeriod.minusMonths(offset);
            BigDecimal income = incomeByMonth.getOrDefault(point, BigDecimal.ZERO);
            BigDecimal expense = expenseByMonth.getOrDefault(point, BigDecimal.ZERO);
            series.add(new MonthlySeriesPoint(point.getYear(), point.getMonthValue(), income, expense));
        }
        return series;
    }

    private static Map<YearMonth, BigDecimal> groupTotalsByMonth(List<MonthlyTotalProjection> projections) {
        return projections.stream().collect(Collectors.toMap(
                projection -> YearMonth.of(projection.getPeriodYear(), projection.getPeriodMonth()),
                MonthlyTotalProjection::getTotal
        ));
    }

    private List<RecentTransactionResponse> buildRecentTransactions(Long userId) {
        PageRequest limit = PageRequest.of(0, RECENT_TRANSACTIONS_LIMIT);
        List<Income> incomes = incomeRepository.findRecentByUserId(userId, limit);
        List<Expense> expenses = expenseRepository.findRecentByUserId(userId, limit);

        Stream<RecentTransactionResponse> incomeStream = incomes.stream().map(income -> new RecentTransactionResponse(
                income.getId(), "INCOME", income.getAmount(), income.getDescription(), income.getDate(),
                income.getCategory() != null ? income.getCategory().getName() : null
        ));
        Stream<RecentTransactionResponse> expenseStream = expenses.stream().map(expense -> new RecentTransactionResponse(
                expense.getId(), "EXPENSE", expense.getAmount(), expense.getDescription(), expense.getDate(),
                expense.getCategory() != null ? expense.getCategory().getName() : null
        ));

        return Stream.concat(incomeStream, expenseStream)
                .sorted(
                        Comparator.comparing(RecentTransactionResponse::date)
                                .thenComparing(RecentTransactionResponse::id)
                                .reversed()
                )
                .limit(RECENT_TRANSACTIONS_LIMIT)
                .toList();
    }

    private static boolean isFoodCategory(String categoryName) {
        if (categoryName == null) {
            return false;
        }
        String normalized = categoryName.toLowerCase(Locale.ROOT);
        return FOOD_CATEGORY_TERMS.stream().anyMatch(normalized::contains);
    }

    private static YearMonth resolvePeriod(Integer year, Integer month) {
        YearMonth now = YearMonth.now();
        int resolvedYear = year != null ? year : now.getYear();
        int resolvedMonth = month != null ? month : now.getMonthValue();
        return YearMonth.of(resolvedYear, resolvedMonth);
    }

    private static BigDecimal nullSafe(BigDecimal value) {
        return value != null ? value : BigDecimal.ZERO;
    }

    private static BigDecimal safeDivide(BigDecimal numerator, BigDecimal denominator) {
        if (numerator == null) {
            return BigDecimal.ZERO;
        }
        if (denominator == null || denominator.compareTo(BigDecimal.ZERO) == 0) {
            return BigDecimal.ZERO;
        }
        return numerator.divide(denominator, RATIO_SCALE, RoundingMode.HALF_UP);
    }
}
