package com.smartfinance.backend.gastos.model.entity;

import com.smartfinance.backend.deudas.model.entity.DebtPayment;
import com.smartfinance.backend.servicios.model.entity.RecurringPayment;
import com.smartfinance.backend.tarjetas.model.entity.CardMovement;
import com.smartfinance.backend.usuario.model.entity.User;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EntityListeners;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;

/**
 * A single expense record owned by a {@link User}.
 *
 * <p>{@link #category} is optional, mirroring {@link Income}: deleting a category does not
 * delete expense history that referenced it (database foreign key uses
 * {@code ON DELETE SET NULL}). {@link #paymentMethod} is required from this entity's
 * introduction, unlike {@link #category} which may be left unclassified.
 *
 * <p>{@link #recurringPayment} is optional and set only for expenses generated by
 * {@code RecurringPaymentService#payRecurringPayment} (the {@code /pay} endpoint introduced in
 * Sprint 3); manually created expenses leave it {@code null}. Deleting the recurring payment
 * does not delete this expense history (database foreign key uses {@code ON DELETE SET NULL}).
 *
 * <p>{@link #debtPayment} is optional and set only for expenses generated by
 * {@code DebtPaymentService#createPayment}; manually created expenses leave it {@code null}.
 * Deleting the debt payment does not delete this expense history (database foreign key uses
 * {@code ON DELETE SET NULL}).
 *
 * <p>{@link #cardMovement} is optional and set only for expenses generated by
 * {@code CardMovementService#registerPurchase} (a card purchase always creates a linked expense,
 * mirroring {@link #debtPayment}). Deleting the card movement does not delete this expense
 * history (database foreign key uses {@code ON DELETE SET NULL}).
 */
@Entity
@Table(name = "expenses")
@EntityListeners(AuditingEntityListener.class)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class Expense {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "category_id")
    private Category category;

    @Column(nullable = false, precision = 15, scale = 2)
    private BigDecimal amount;

    @Column(length = 255)
    private String description;

    @Column(name = "date", nullable = false)
    private LocalDate date;

    @Enumerated(EnumType.STRING)
    @Column(name = "payment_method", nullable = false, length = 20)
    private PaymentMethodType paymentMethod;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "recurring_payment_id")
    private RecurringPayment recurringPayment;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "debt_payment_id")
    private DebtPayment debtPayment;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "card_movement_id")
    private CardMovement cardMovement;

    @CreatedDate
    @Column(name = "created_at", updatable = false)
    private Instant createdAt;

    @LastModifiedDate
    @Column(name = "updated_at")
    private Instant updatedAt;
}
